[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wequant"    # PyPIで配布するときの名前（プロジェクト専用でpypiには登録しないため不要だが、nameは必須）
version = "0.1.0"
description = "wequant stock market analysis"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "jupyterlab",
  "pandas>=2.2.3",
  "plotly",
  "polars-lts-cpu",
  "pyarrow",
  "pydantic",
  "python-dotenv",
  "requests",
  "typer",
]

[project.scripts]
wq = "wequant.cli:app"  # ← これで `pa` コマンドができる

[tool.setuptools.packages.find]
include = ["wequant"]
